name = "modpacsito"
author = "jansell29"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d347c43e6079d15f414d3a15851ad61700635c68ebdcee12e716a97b9d3ea19"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
